### ISSUE TITLE
Missing titles on "Waiting for new volumes"

### ISSUE THREAD

**Issue by maidoinhevun** [pgr3931/manga-overview#1]
When I created my account on the webpage, it worked all fine and exported everything on my paused list + reading. After a short period of time, and after removing a few of the reading titles that I'm reading on Manga PLUS, the whole list disappeared leaving only 1 title on reading and another on the waiting for new volumes. Revoked the token, deleted and made again the list and now only 6 mangas appears on my "waiting for new volumes" part (I have around 11 on AL's list, and all of them are paused).
![image](https://user-images.githubusercontent.com/78202678/196041565-076105fc-ddf5-4dad-aa1e-e2c8a00d4603.png)
This is how the list looks like.
![image](https://user-images.githubusercontent.com/78202678/196041583-204fa72d-a9b0-43f5-b0ec-bd0b318fab15.png)
This is how it looks on Manga Bai.
![image](https://user-images.githubusercontent.com/78202678/196041625-3c3588f5-e6e3-40e9-ac34-5f7b55f030bd.png)
And they are not even here neither.

**Comment by lgrones** [comment]
Thanks for creating this issue. I'll look into it as soon as I find some time. Always happy for PRs too.

Can you give me your username on AniList? That would make cross-checking the issue easier. Thanks!

**Comment by maidoinhevun** [comment]
First of, thank you for your fast reply. Wasn't expecting it to be less than 12h lol. As for my username, is BetterBegoneThot -I doubt there's anyone else called like that, so I won't add a link. Again, thank you for your time.

**Comment by maidoinhevun** [comment]
Another update: I've setted Madoka Magica Wraith Arc (it can be seen on the screenshot as reading) on hold since I've already read what I have on physical format. Even if I manually put it on the custom list, the website doesn't update that manga as "waiting for new volumes", but it did deleted it from "reading". Note: I've updated by the desktop AL website, if that could mean anything.

**Comment by lgrones** [comment]
Should be fixed with commit [#2de7a67161d3864af3028ba51004195a56416e2d](https://github.com/pgr3931/manga-bai/commit/2de7a67161d3864af3028ba51004195a56416e2d). The fixed version is already deployed.

The issue was that your custom list "[🛑] Shelf - LF next volume" had a complete subset of the entries in Manga Bai's custom list, which confused the filter checking for those entries.

Also let me take this chance to thank you for using Manga Bai :) New Features are coming soon™
