### ISSUE TITLE
new volume available

### ISSUE THREAD

**Issue by carb0n0x** [pgr3931/manga-overview#4]
The "new volume available" icon seems to be showing up only for manga with relatively recent releases, any way to make it show up even with old releases if I'm behind in reading/preorder progress?

**Comment by lgrones** [comment]
Thanks for the bug report!

It shouldn't matter how old a release is, the app simply looks for the next volume in the series.

But there could be a few reasons for this happening:

1. The check for new volumes is rate-limited by Google. That means depending on the size of your list, the check might take a few minutes. You could trying waiting a bit to see if the that helps.
2. Google might not have that particular series in its database, which means the app can't find out if there is a new volume available
3. There might be a bug in the app itself

Either way to find out what's going on I need to know which manga you're talking about :)

**Comment by carb0n0x** [comment]
I don't think it's "1." since I only added a few random manga I have read and/or dropped to see if it worked, and the app shows results immediately after i change any value or add a new series.
I tried changing every volume to progress/preorder 1/1 (every series in this list has at least 2 volumes) and you can see for yourself it's 50% chance.
![2022-12-20-19-24-46](https://user-images.githubusercontent.com/48187643/208741752-f9268bc8-5e69-4a44-8adc-e81da31e1dcc.jpg)

Here's the list in english if you can't read japanese (shortened some cause I'm lazy):
>ichigo mashimaro - NEW VOLUME AVAILABLE
>adamas no majotachi - NEW VOLUME AVAILABLE
>gaishuu isshoku
>isekai meikyuu de harem wo
>kao ni denai kashiwada-san
>ittsumo shiotaiou
>sewayaki kitsune no Senko-san
>Mieruko-chan - NEW VOLUME AVAILABLE
>Idolmaster CinderelLa Girls U149
>Suki na ko ga megane wasureta - NEW VOLUME AVAILABLE
>D-frag - NEW VOLUME AVAILABLE
>Shakunetsu no Takkyuu Musume
>Machikado Mazoku - NEW VOLUME AVAILABLE
>Gacha wo Mawashite - NEW VOLUME AVAILABLE
>Kono healer medokusai
>Wazawai Kitsune no Kuzure-chan
>Choukadou Girls
>Isekai Ojisan - NEW VOLUME AVAILABLE
>Boukensha ni Naritai

**Comment by lgrones** [comment]
Japanese is fine, no worries - still thanks for goinfg through the effort of converting them :)

I'll definitely look into it and come back to you as soon as I have an explanation for this behavior

**Comment by lgrones** [comment]
Just one more question: Since you have your entries in Japanese, do you want to get checks for Japanese volumes? If so you'd need to change that in the settings of the entry. The entries that don't show a next volume are all series that are not published in English. The others do have English releases.

![image](https://user-images.githubusercontent.com/45991112/209069817-dd46d7e1-5a18-4703-a46a-f21f5fc08118.png)

**Comment by carb0n0x** [comment]
Yes I wanted to check for jp volumes updates, and yes that worked!
I thought if I saved the titles in native language it would automatically link the update check to the jp side of google/amazon, my bad for not checking it. All titles now show new volume available as intended and are up to date, thanks!
